### ISSUE TITLE
Gilab hides some output

### ISSUE THREAD

**Issue by tsusanka** [trezor/trezor-user-env#27]
https://gitlab.com/satoshilabs/trezor/connect/-/jobs/798163842#L93

Why are `<Message>` item hidden from the emulator log?

On my machine:
`173064472861 trezor.wire DEBUG 1:0 receive: <DebugLinkGetState>`

On CI:
`173064472861 trezor.wire DEBUG 1:0 receive: `

-----

This exception was hidden on CI but present on my machine, why?

```
Exception happened during processing of request from ('127.0.0.1', 45882)
Traceback (most recent call last):
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/trezor-user-env/controller/websocket_server.py", line 168, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/nix/store/q732h09azy7lf0j30bnnhdl15p4rxpdy-python3-3.7.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/trezor-user-env/controller/websocket_server.py", line 182, in handle
    self.read_next_message()
  File "/trezor-user-env/controller/websocket_server.py", line 245, in read_next_message
    opcode_handler(self, message_bytes.decode("utf8"))
  File "/trezor-user-env/controller/websocket_server.py", line 128, in _message_received_
    self.message_received(self.handler_to_client(handler), self, msg)
  File "controller/main.py", line 79, in message_received
    cmd.get("needs_backup"),
  File "/trezor-user-env/controller/emulator.py", line 110, in setup_device
    needs_backup=bool(needs_backup),
  File "/nix/store/9sy7hhj7wk66lsq2fwkxwjn1ywxs5fwc-python3-3.7.7-env/lib/python3.7/site-packages/trezorlib/tools.py", line 202, in wrapped_f
    ret = f(*args, **kwargs)
  File "/nix/store/9sy7hhj7wk66lsq2fwkxwjn1ywxs5fwc-python3-3.7.7-env/lib/python3.7/site-packages/trezorlib/debuglink.py", line 545, in load_device
    no_backup=no_backup,
  File "/nix/store/9sy7hhj7wk66lsq2fwkxwjn1ywxs5fwc-python3-3.7.7-env/lib/python3.7/site-packages/trezorlib/tools.py", line 223, in wrapped_f
    return f(client, *args, **kwargs)
  File "/nix/store/9sy7hhj7wk66lsq2fwkxwjn1ywxs5fwc-python3-3.7.7-env/lib/python3.7/site-packages/trezorlib/client.py", line 221, in call
    resp = self._callback_button(resp)
  File "/nix/store/9sy7hhj7wk66lsq2fwkxwjn1ywxs5fwc-python3-3.7.7-env/lib/python3.7/site-packages/trezorlib/client.py", line 208, in _callback_button
    self.ui.button_request(msg.code)
  File "/nix/store/9sy7hhj7wk66lsq2fwkxwjn1ywxs5fwc-python3-3.7.7-env/lib/python3.7/site-packages/trezorlib/debuglink.py", line 221, in button_request
    self.debuglink.wait_layout()
  File "/nix/store/9sy7hhj7wk66lsq2fwkxwjn1ywxs5fwc-python3-3.7.7-env/lib/python3.7/site-packages/trezorlib/debuglink.py", line 63, in wait_layout
    return layout_lines(obj.layout_lines)
AttributeError: 'Failure' object has no attribute 'layout_lines'
```

**Comment by darwin** [comment]
I don't see the issue on the [posted link](https://gitlab.com/satoshilabs/trezor/connect/-/jobs/798163842). It looks like gitlab folks have fixed this on their end.

**Comment by tsusanka** [comment]
Huh, interesting. I have also updated dependencies [here](https://github.com/trezor/trezor-user-env/commit/4380d5d78d320d097a71fbb4300fd8987eb1fc2f) so it can be that as well. Thanks, closing.
